CATALOGUE_HOST: catalogue.backend-{{ env }}.daws84.space
USER_HOST: user.backend-{{ env }}.daws84.space
CART_HOST: cart.backend-{{ env }}.daws84.space
SHIPPING_HOST: shipping.backend-{{ env }}.daws84.space
PAYMENT_HOST: payment.backend-{{ env }}.daws84.space